### ISSUE TITLE
NPM Install Error: Possible missing/private packages.

### ISSUE THREAD

**Issue by bobbyshaw** [magento-research/venia-pwa-concept#52]
Hi, 

I've followed setup instructions of https://github.com/paliarush/magento2-vagrant-for-developers and https://github.com/magento-research/venia-pwa-concept/

I have successfully configured the theme and see the venia root template when visiting the store frontend. 

From within the vagrant box I run `npm install` inside `magento2ce/app/design/frontend/Magento/venia` but I get the following error around where it tries to install the Magento packages:

```
1108 http 404 https://registry.npmjs.org/magento/peregrine
1109 silly registry.get cb [ 404,
1109 silly registry.get   { 'content-type': 'application/json',
1109 silly registry.get     'cache-control': 'max-age=0',
1109 silly registry.get     'content-length': '2',
1109 silly registry.get     'accept-ranges': 'bytes',
1109 silly registry.get     date: 'Tue, 01 May 2018 19:49:11 GMT',
1109 silly registry.get     via: '1.1 varnish',
1109 silly registry.get     age: '0',
1109 silly registry.get     connection: 'keep-alive',
1109 silly registry.get     'x-served-by': 'cache-lhr6351-LHR',
1109 silly registry.get     'x-cache': 'MISS',
1109 silly registry.get     'x-cache-hits': '0',
1109 silly registry.get     'x-timer': 'S1525204151.030222,VS0,VE678',
1109 silly registry.get     vary: 'Accept-Encoding' } ]
1110 silly addNameRange number 2 { name: 'magento/pwa-buildpack',
1110 silly addNameRange   range: '>=0.6.0-0 <0.7.0-0',
1110 silly addNameRange   hasData: true }
1111 silly addNameRange versions [ undefined, [] ]
1112 error TypeError: Cannot read property 'latest' of undefined
1112 error     at next (/usr/share/npm/lib/cache.js:687:35)
1112 error     at /usr/share/npm/lib/cache.js:675:5
1112 error     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
1112 error     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
1112 error     at Object.oncomplete (fs.js:107:15)
1113 error If you need help, you may report this log at:
1113 error     <http://github.com/isaacs/npm/issues>
1113 error or email it to:
1113 error     <npm-@googlegroups.com>
1114 error System Linux 3.13.0-85-generic
1115 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
1116 error cwd /Users/tomrobertshaw/Code/venia-pwa-concept/theme-frontend-venia
1117 error node -v v0.10.25
1118 error npm -v 1.3.10
1119 error type non_object_property_load
1120 verbose exit [ 1, true ]
```

When I visit the NPM registry package urls in a browser, i.e. https://registry.npmjs.org/magento/peregrine, https://registry.npmjs.org/magento/pwa-buildpack and https://registry.npmjs.org/magento/eslint-config, I see an empty JSON object. My limited knowledge of npm suggests to me that it can't find the Magento packages to install(?).

This is strange as @rossmc appeared to get past this step in #51. Did something change, or have I made a mistake or missed a step along the way?

Many thanks! Looking forward to getting involved.

**Comment by rossmc** [comment]
just a thought, but what version of node are you using [pwa-buildpack ](https://github.com/magento-research/pwa-buildpack)requieres NodeJS 8.x

**Comment by DrewML** [comment]
@rossmc good call - line 1117 in the error log abouve shows node `0.10.x`.

@bobbyshaw if you upgrade to the current LTS version (`8.x`) it should get you past that particular issue.

If you're on MacOS/Linux, would recommend using [nvm](https://github.com/creationix/nvm). If on Windows, I've heard [`nvm-windows`](https://github.com/coreybutler/nvm-windows) works out alright.

**Comment by bobbyshaw** [comment]
Thanks, I've come from the docker world where everything is run in containers and not on the host machine.

The vagrant repo (https://github.com/paliarush/magento2-vagrant-for-developers) provides more documentation on using `n` to install and use other node versions. While it doesn't seem like it's installed as advertised I was able to install manually by cloning the repo and running `sudo make install` and then `sudo n latest`. 

That got me up and running, or at least got me to the same error as in #51 so I'll follow that one now. 

Thanks!
