### ISSUE TITLE
Routing resolve failed  Error: 404  at eval (MagentoRouteHandler.js?76f8:67)

### ISSUE THREAD

**Issue by rossmc** [magento-research/venia-pwa-concept#59]
I've just tried setting this up again with a new _magento2-vagrant-for-developers_ box which is using the 2.3-develop branch of Magento, to overcome an error I was getting as graphql is not included in 2.2.

Anyway, I'm now getting the following error in my browser when I visit https://magento-venia.local.pwadev:8000/ 
```
Routing resolve failed
 Error: 404
    at eval (MagentoRouteHandler.js?76f8:67)
```
<img width="1440" alt="screen shot 2018-05-04 at 23 27 22" src="https://user-images.githubusercontent.com/2452991/39655905-53d4b08a-4ff4-11e8-9a38-1b03a676d371.png" style="max-width:80%; margin:auto">

I tried opening https://magento-venia.local.pwadev:8000/home as suggested by @matthewhaworth  in #51 but that gives the following console error in my browser:
```
GET https://magento-venia.local.pwadev:8000/pub/static/frontend/Magento/venia/roots-manifest.json 404 ()
Routing resolve failed
 SyntaxError: Unexpected token < in JSON at position 0
    at eval (resolveUnknownRoute.js?27f5:68)
```

I checked the /graphql path in both https://magento-venia.local.pwadev:8000/graphql and http://magento2.vagrant193/graphql and they both display the following in the browser...
```
{
   "errors":[
      {
         "debugMessage":"Request content type must be application\/json",
         "message":"Internal server error",
         "category":"internal",
         "trace":[
            {
               "file":"\/Users\/ross\/Projects\/magento2-vagrant-for-developers\/magento2ce\/app\/code\/Magento\/GraphQl\/Controller\/HttpRequestProcessor.php",
               "line":39,
               "call":"Magento\\GraphQl\\Controller\\HttpHeaderProcessor\\ContentTypeProcessor::processHeaderValue((empty string))"
            },
            {
               "file":"\/Users\/ross\/Projects\/magento2-vagrant-for-developers\/magento2ce\/app\/code\/Magento\/GraphQl\/Controller\/GraphQl.php",
               "line":101,
               "call":"Magento\\GraphQl\\Controller\\HttpRequestProcessor::processHeaders(instance of Magento\\Framework\\App\\Request\\Http)"
            },
            {
               "file":"\/Users\/ross\/Projects\/magento2-vagrant-for-developers\/magento2ce\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php",
               "line":58,
               "call":"Magento\\GraphQl\\Controller\\GraphQl::dispatch(instance of Magento\\Framework\\App\\Request\\Http)"
            },
            {
               "file":"\/Users\/ross\/Projects\/magento2-vagrant-for-developers\/magento2ce\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php",
               "line":138,
               "call":"Magento\\GraphQl\\Controller\\GraphQl\\Interceptor::___callParent('dispatch', array(1))"
            },
            {
               "file":"\/Users\/ross\/Projects\/magento2-vagrant-for-developers\/magento2ce\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php",
               "line":153,
               "call":"Magento\\GraphQl\\Controller\\GraphQl\\Interceptor::Magento\\Framework\\Interception\\{closure}(instance of Magento\\Framework\\App\\Request\\Http)"
            },
            {
               "file":"\/Users\/ross\/Projects\/magento2-vagrant-for-developers\/magento2ce\/generated\/code\/Magento\/GraphQl\/Controller\/GraphQl\/Interceptor.php",
               "line":26,
               "call":"Magento\\GraphQl\\Controller\\GraphQl\\Interceptor::___callPlugins('dispatch', array(1), array(1))"
            },
            {
               "file":"\/Users\/ross\/Projects\/magento2-vagrant-for-developers\/magento2ce\/lib\/internal\/Magento\/Framework\/App\/Http.php",
               "line":135,
               "call":"Magento\\GraphQl\\Controller\\GraphQl\\Interceptor::dispatch(instance of Magento\\Framework\\App\\Request\\Http)"
            },
            {
               "file":"\/Users\/ross\/Projects\/magento2-vagrant-for-developers\/magento2ce\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php",
               "line":24,
               "call":"Magento\\Framework\\App\\Http::launch()"
            },
            {
               "file":"\/Users\/ross\/Projects\/magento2-vagrant-for-developers\/magento2ce\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php",
               "line":256,
               "call":"Magento\\Framework\\App\\Http\\Interceptor::launch()"
            },
            {
               "file":"\/Users\/ross\/Projects\/magento2-vagrant-for-developers\/magento2ce\/index.php",
               "line":39,
               "call":"Magento\\Framework\\App\\Bootstrap::run(instance of Magento\\Framework\\App\\Http\\Interceptor)"
            }
         ]
      }
   ]
}
```

In the chrome network tab, the graphql response simply shows `{"data":{"urlResolver":null}}`

The above seems to indicate the issue is with Magento 2.3's graphQL response.

Has anyone else come across this?  Is this more of an issue with Magento 2.3's graphQL rather than PWA Studio?  Or hopefully I'm just missing out on a simple step to get it working.

**Comment by philaturner** [comment]
@rossmc 
Updating my env file as per the below helped me
`MAGENTO_BACKEND_PUBLIC_PATH="https://cetwothree.test/static/frontend/Magento/venia/en_US/js/"`
As i was seeing a base URL error within `tempGetWebpackChunkData()` inside `app/design/frontend/Magento/venia/node_modules/@magento/peregrine/dist/Router/resolveUnknownRoute.js`

https://cetwothree.test/home
Gives a graphql response as below for me
`{"data":{"urlResolver":{"type":"CMS_PAGE"}}}`

**Note** I'm using `npm run build`

Hopefully helps you out in some form

**Comment by rossmc** [comment]
Thanks @philaturner but that gives me a different error...
```
Uncaught ReferenceError: webpackJsonp is not defined
    at client.js:1
```
I'm checking it on the vagrant magento url, i.e. http://magento2.vagrant193.  I also had to change the path to client.js in the root.phtml template for it to get the error above...
```
   <body>
     <div id="root"></div>
-    <script src="/pub/static/frontend/Magento/venia/en_US/client.js"></script>
+    <script src="/pub/static/frontend/Magento/venia/en_US/js/client.js"></script>
   </body>
```

So I take it you're not using the webpack dev server? i.e. https://magento-venia.local.pwadev:8000/

**Comment by philaturner** [comment]
@rossmc 
Afraid I'm not using the dev server was just throwing that above as a means to hopefully help.

I'll have a play with the dev server in the next day or two to see if I can re-create/fix it.

**Comment by rossmc** [comment]
No problem @philaturner, thanks for the suggestion.  It was helpful all the same :)

**Comment by philaturner** [comment]
@rossmc 
So i setup a fresh new environment to remove any variables from my current one.

Everything seems to be working with a few minor ammends, I'll drop below what I've changed files wise and see how you get on.

Cloned magento2 from github and checkout branch `2.3-develop`
Installed dependancies with yarn vs. npm (always seem to have better results generally speaking)

**.env file contents**
```
MAGENTO_BACKEND_DOMAIN="http://ventest.test/"
MAGENTO_BACKEND_PUBLIC_PATH="/static/frontend/Magento/venia/en_US/js/"
SERVICE_WORKER_FILE_NAME="sw.js"
```
**updated** `magento2/app/design/frontend/Magento/venia/Magento_Theme/templates/root.phtml` with
```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Try not to put things in this file.
 */

// @codingStandardsIgnoreFile
/** @var $block Magento\Pwa\Block\Bundle */
?>
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Venia</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div id="root"></div>
    <script src="/static/frontend/Magento/venia/en_US/js/client.js"></script>
  </body>
</html>
```

Always worth cleaning your cache before you run `npm start` - `bin/magento cache:clean`

Visiting `/home` works
and also created a test product in the admin with the URL `/test-product.html` and I'm getting the product root components too
`https://magento-venia.local.pwadev:8000/test-product.html`

**Issues**
I am getting an `ENOENT` error on `sw.js` but frontend wise seems to work ok, so not really sure on that bit.

Hope this help you - not sure if you reindexed and also cleaned cache; this seemed to help me out alot.

**Comment by rossmc** [comment]
awesome, thanks @philaturner will try that later and see how I get on.

One thing, do you have ssl on your magento site?

**Comment by philaturner** [comment]
@rossmc 
Good luck 😄 
On my original environment I do, but on this (above) new fresh one i do not, so it just serving over `http`

**Comment by DrewML** [comment]
> awesome, thanks @philaturner will try that later and see how I get on.

@rossmc let us know if things don't work out and we'll continue debugging.

> On my original environment I do, but on this (above) new fresh one i do not, so it just serving over http

@philaturner if you're having troubles with the auto-provisioned SSL, we'd love to know so we can address the issue for you + others. Don't hesitate to open a new issue if you don't get things figured out, or if there are improvements we could make.

**Comment by philaturner** [comment]
@DrewML auto-provisioned SSL is fine for me, but the service worker seems to sometimes work and sometimes 404.  I'll open another once I understand it more.

**Comment by rossmc** [comment]
got it working in the end :)

@DrewML, is the Nav meant to work yet? When I click on the header NavTrigger, I see the event is logged as TOGGLE_NAVIGATION by `@magento/peregrine/dist/store/middleware/log.js` but `this.props.nav` is not updated in `src/components/Navigation/navigation.js` by `store/reducers/navigation.js`

_I've only recently started learning React and have just skimmed the surface of redux_

**Comment by DrewML** [comment]
@rossmc it doesn't work at the moment. @jimbo is working on refactoring things a bit, so it'll get there :).
