### ISSUE TITLE
Review and removal of UX prototype references (pwaza) in Venia theme

### ISSUE THREAD

**Issue by ericerway** [magento-research/venia-pwa-concept#65]
Removal of one last "pwaza" from the Venia theme. Need to replace with proper image not referenced in the early prototype. Thanks!

magento-research/venia-pwa-concept – mockData.js

AC
Update pwaza reference in venia-pwa-concept
Review and address any remaining references including magento-ux.github.io
Test and document as necessary

**Comment by jimbo** [comment]
Addressing in #67.

This isn't quite so simple as removing a pwaza reference, unfortunately. The images were hosted there; now that they're gone, we need to host them elsewhere. If we serve them from webpack, there's a bit more to it, but that's the approach we're going to take for now.

**Comment by DrewML** [comment]
Merged #67.
