### ISSUE TITLE
Typo in Pwa/Model/Result/JSFileResult.php

### ISSUE THREAD

**Issue by bgkavinga** [magento-research/venia-pwa-concept#81]
## This issue is a:
[x ] Bug
[ ] Feature suggestion
[ ] Other
 

## Description:
Pwa/Model/Result/JSFileResult.php should be Pwa/Model/Result/JsFileResult.php with lower case `s`

 

## Expected result:
Request url sw.js should return sw.js file under venia/web/js/sw.js

**Comment by DrewML** [comment]
@bgkavinga: it's not clear to me what the `Expected Result` has to do with the `Description` of this bug. Can you clarify?

**Comment by bgkavinga** [comment]
Hi @DrewML ,
This file is injected in Magento\Pwa\Controller\Index\Js which serve the sw.js file. With this typo, it fails to inject the  \Magento\Pwa\Model\Result\JsFileResultFactory which fails the delivery of sw.js file.
![image](https://user-images.githubusercontent.com/3830093/40957280-fb94f78c-68b1-11e8-8907-884ddba59b8f.png)
